Update LiveScriptCode

diff --git a/LiveScriptCode b/LiveScriptCode
--- a/LiveScriptCode
+++ b/LiveScriptCode
@@ -2,8 +2,7 @@
 ROOM_ID=""
 
 #Put your Hipchat API token here if the first script did not do it
-AUTH_TOKEN_NOTIFICATION=
-AUTH_TOKEN_CREATEROOM=
+AUTH_TOKEN_Slack=
 
 #Put your Hipchat API token here if the first script did not do it
 AUTH_TOKEN_BITLY=
@@ -30,8 +29,6 @@ while [[ "$CHOICEBRAND" != [12] ]]; do
   read CHOICEBRAND
 done
 [[ $CHOICEBRAND = 1 ]] && brand="MOONPIG" || brand="PHOTOBOX"
-# Selecting the Hipchat Main Room
-[[ $CHOICEBRAND = 1 ]] && ROOM_ID=635285 || ROOM_ID=795977 
 
 #Selection if retro
 #Loop until value 1 or 2 is selected
@@ -104,23 +101,19 @@ if [[ $confirmation =~ ^(y|Y|Yes|YES)$ ]]; then
     # Opening room if not a retro code
     if [[ $CHOICERETRO = 2 ]]; then
       # limiting the name to 50 caracters
-      HIPNAMECUT=$(echo "$brand - Code $color - $number - $name" | awk '{print substr($0,0,49)}')
-      if [[ $? != 0 ]]; then echo ""; echo "!!!!!! An error occured getting 50 caracters for hipchat room name !!!!!!" ; fi
+      #if [[ $? != 0 ]]; then echo ""; echo "!!!!!! An error occured getting 50 caracters for hipchat room name !!!!!!" ; fi
       # Opening Room
-      echo '------------------------------------Open Room------------------------------------'
-      curl -s -H "Content-Type: application/json" \
-      -X POST \
-      -d "{\"name\": \"$HIPNAMECUT\" , \"topic\": \"$DebriefLink\"}" \
-      https://api.hipchat.com/v2/room?auth_token=$AUTH_TOKEN_CREATEROOM  >> /dev/null
+      echo '------------------------------------Open Channel------------------------------------'
+      wget https://slack.com/api/channels.create?token=$AUTH_TOKEN_Slack\&name=Code-$CHOICECOLOR-$number >/dev/null 2>&1
       if [[ $? != 0 ]]; then echo ""; echo "!!!!!! An error occured creating the room !!!!!!" ; fi
     else
-      echo "No room for Retrocodes"
+      echo "No Channel for Retrocodes"
     fi
     
     echo '------------------------------------FOR NOC2------------------------------------'
     if [[ $CHOICERETRO = 2 ]]; then
       echo "Debrief Doc: $DebriefLink"
-      echo "Hipchat Room: Test $brand - Code $color - $number - $name"
+      echo "Slack Channel : Test  - Code-$CHOICECOLOR-$number"
     else
       echo "Debrief Doc: $DebriefLink"
     fi
@@ -135,10 +128,11 @@ if [[ $confirmation =~ ^(y|Y|Yes|YES)$ ]]; then
     read confirmation2
     if [[ $confirmation2 =~ ^(y|Y|Yes|YES)$ ]]; then
             echo '------------------------------------Send message for room opened------------------------------------'
-            curl -s -H "Content-Type: application/json" \
-            -X POST \
-            -d "{\"color\": \"gray\", \"message_format\": \"text\", \"message\": \"@here New Code opened : Test Code $color - $number - $name \" }" \
-            https://api.hipchat.com/v2/room/$ROOM_ID/notification?auth_token=$AUTH_TOKEN_NOTIFICATION
+            #curl -s -H "Content-Type: application/json" \
+            #-X POST \
+            #-d "{\"color\": \"gray\", \"message_format\": \"text\", \"message\": \"@here New Code opened : Test Code $color - $number - $name \" }" \
+            #https://api.hipchat.com/v2/room/$ROOM_ID/notification?auth_token=$AUTH_TOKEN_NOTIFICATION
+            wget https://slack.com/api/chat.postMessage?token=$AUTH_TOKEN_Slack\&channel=noctestcode\&text='Test Code-$CHOICECOLOR-$number has been opened'\&as_user=true >/dev/null 2>&1
             if [[ $? != 0 ]]; then echo ""; echo "!!!!!! An error occured send notification to the main room !!!!!!" ; fi
     else
         echo "You have selected not to send the communication on the main room"
