Update LiveScriptCode

diff --git a/LiveScriptCode b/LiveScriptCode
--- a/LiveScriptCode
+++ b/LiveScriptCode
@@ -85,8 +85,15 @@ if [[ $confirmation =~ ^(y|Y|Yes|YES)$ ]]; then
       if [[ $? != 0 ]]; then echo ""; echo "!!!!!! An error occured duplicating the debrief doc !!!!!!" ; fi
     fi
     echo '------------------------------------New Debrief Doc------------------------------------'
-    URLDebrief=`drive url 'Noc-Support/In Progress/Testduplicate/Code '$color' '$number' Debrief'| awk '{print $6}'`
-    if [[ $? != 0 ]]; then echo ""; echo "!!!!!! An error occured getting the debrief URL !!!!!!" ; fi
+    if [[ CHOICEBRAND = 1 ]]; then 
+      #Moonpig debrief
+      URLDebrief=`drive url 'PBX, S9 and HF Code Debrief documents/Moonpig Code Debrief documents '$color' '$number' Debrief'| awk '{print $6}'`
+      if [[ $? != 0 ]]; then echo ""; echo "!!!!!! An error occured duplicating the debrief doc !!!!!!" ; fi
+    else
+      # Photobox debrief
+      URLDebrief=`drive url 'PBX, S9 and HF Code Debrief documents '$color' '$number' Debrief'| awk '{print $6}'`
+      if [[ $? != 0 ]]; then echo ""; echo "!!!!!! An error occured duplicating the debrief doc !!!!!!" ; fi
+    fi
     echo $URLDebrief
 
     # Creation bitly link
